### ISSUE TITLE
django-sanction on django 1.5

### ISSUE THREAD

**Issue by johnjwatson** [demianbrecht/django-sanction#2]
Hi Damian,

Not sure if this issue is specific to me, but when I try django-sanction on django 1.5 (fresh install) and do a syncdb, I get:

CommandError: One or more models did not validate:
auth.user: The USERNAME_FIELD must be unique. Add unique=True to the field parameters.

So, I went ahead and changed:
BaseUser._meta.get_field("username")._unique = False
to:
BaseUser._meta.get_field("username")._unique = True

..and then it seems to work (i.e syncdb).

p.s: It would be good to have a google groups for django-sanction :)

**Comment by demianbrecht** [comment]
I haven't had the time yet to get django-sanction caught up to 1.5 yet (including Python 3.x support), so there may be some issues there. If you encounter any and have fixed them, feel free to submit a patch.

As for Google groups, I'm not sure that 10 followers and a whole 350'ish installs via PyPI really warrants it ;). The Django list would be an appropriate place to ask such questions though.

I'll leave this issue open for now, pending patch submission or me having time to do it. Thanks for the heads up.

**Comment by johnjwatson** [comment]
Thanks for your reply. I could submit a patch, but I should warn you that I am a django newbie (in fact learning django through your package). If you could review the patch I submit, it would help.

**Comment by demianbrecht** [comment]
After a little thought, I believe that I had monkey-patched username field for a reason (multiple providers potentially using the same email address). This may have to be reworked a little, so I'll take a look at this sooner than later.

**Comment by johnjwatson** [comment]
Currently, what I do in line 20, auth.py is:

```
if created:
    # username should be either set by the user or 
    # by application logic
    from random import randint
    user.username = "user" + str(randint(1e2, 1e6))
```

So I just create a username with a random number - It seems to work so far - not sure if this should be the right approach.

**Comment by demianbrecht** [comment]
Closing this as it's no longer valid.
