### ISSUE TITLE
create superuser fails.

### ISSUE THREAD

**Issue by johnjwatson** [demianbrecht/django-sanction#3]
Hi Damian,

Today I have started to try out your newer version of django-sanction and I have come across a small problem. So, once I set everything up as per your example, and try syncdb, I get:
TypeError: create_superuser() takes exactly 4 arguments (3 given)

Not sure why this is (maybe I am being stupid here) - but my guess is it is something to do with custom user model(?). I was wondering if you could enlighten me on how to get rid of this error.

Thanks again for all your help with this.

**Comment by demianbrecht** [comment]
The example User model was only intended to demonstrate creating a custom user that implemented the API required by the OAuth 2.0 system, not Django's auth contrib module. If you'd like to modify it to work, by all means, make modifications locally and contribute a patch.

Closing this as it wasn't intended to be in the scope of the example project.

**Comment by johnjwatson** [comment]
Hi Damian,

I will submit a patch - but I need to know what is wrong with this example I suppose. 
So, straight after I install your example and run "python manage.py syncdb" I get the:
TypeError: create_superuser() takes exactly 4 arguments (3 given)

So, I have not modified anything - It is straight off your package.
I wonder if I need a custom user manager?
If you could give me some clues (at the moment I am unsure where the problem lies - your models.py looks OK to me), I will sort the example and submit a patch.

**Comment by johnjwatson** [comment]
OK - I have sorted the example - I will contribute a patch soon.

**Comment by demianbrecht** [comment]
Apologies for not getting back to you sooner. There are a few things that need to happen:

The custom User model needs to have the attributes that the Django admin app looks for (i.e. email).

Fundamentally, the concept of creating a super user and the way the contained example is implemented clash: The base sanction user does't have an email address, it's part of the "current provider". One possible solution might be to have a "main" provider (one that's used for initial login), which is used as the users' email attribute.

Another issue is that sanction users don't have passwords (wouldn't make sense as authentication is done by the provider). So, if you're using both methods of authentication, you now have a single model acting as a base for two distinct functions. While it works, I'm not sure it's the best way to go (although there may be no alternative, I'm pretty sure it's not possible to define more than one user model as the custom user model and route based on requirements).

Then there are the issues of getting contrib auth's User model functionality required for authorization (what access each individual user has). If you're combining OAuth users with "native" users, then they should be both handled in the same way. You might be able to simply monkeypatch the custom user model with methods from contrib auth's User, but I'm not sure whether or nto it would actually work.

Anyway, those are immediate thoughts off the top of my head.

**Comment by johnjwatson** [comment]
Hi Demian,

Thank you for your thoughts here.
So, I have made a small start, and here is my example models.py (I borrowed code from custom_user.py):
https://gist.github.com/johnjwatson/5442906

It seems to work.. Well, at least the superuser is created.
I will keep you posted!
Thanks for all your help.
