### ISSUE TITLE
client.token_expires or client.expires_in

### ISSUE THREAD

**Issue by johnjwatson** [demianbrecht/django-sanction#4]
Hi Demian,

Sorry to come up with another two issues:

[1] In fetch_google method, you have:
'token_expires': client.token_expires,
..this does not seem to work. However:
'token_expires': client.expires_in,
..works just fine. Can you comment on this please?

[2] After I make the above change [1], and try the google login, I get:
403 Forbidden 
and the logging error:
ERROR:root:Unable to authenticate user
I wonder why this is happening :(

**Comment by demianbrecht** [comment]
My bad. If you're using the Github version of Sanction, I had forgotten to commit 0.3.1, which contains the default refresh_token and token_expires implementation. That's now been committed.

Essentially, if a providers' implementation adheres to the RFC (expires_in), then the token_expires attribute is set automatically by the underlying sanction client implementation during the request_token flow (that's demonstrated in the google flow). If it doesn't, then it has to be set in your code (i.e. facebook flow).

The above may also be why you're running into the second issue.

**Comment by johnjwatson** [comment]
Hi Demian,

Thank you for your reply.

So, [1] seems to solved now (yes, I was using sanction from your Github, reinstalled this now) i.e token_expires implementation works.

The second issue still remains - I after authorization, I get:
ERROR:root:Unable to authenticate user
[23/Apr/2013 12:31:15] "GET /o/login/google?state=qfSqzIvutjkPvN1bFUpKxaVUDEjmS187&code=4/IaQNvC2K7YbImSPlAgM1S9K_YDY6.gmkJ1tIR_YoUOl05ti8ZT3bZkVZtfAI HTTP/1.1" 403 22

Presumably this is generated because user is returned as None in your django_sanction/views.py (line 81)..
I will keep looking on how to solve this..

**Comment by johnjwatson** [comment]
Hi Demian,

Sorry to bother you again, but, why does the call [line81, views.py]: 
authenticate(code=request.GET['code'], provider_key=provider) 
...to the authenticate() method return None?
This seems to be the showstopper..and I keep getting 403 forbidden!
I would really appreciate it if you could point me in the right direction to solve this issue..

**Comment by demianbrecht** [comment]
Are you trying to just run the example app? The call to `authenticate` should return `None` if `[UserInstance].fetch_user` returns `None`.

**Comment by johnjwatson** [comment]
Got it!. It all works just fine! So, I have done a reasonable example (I think) with google. I will now attempt facebook login. You can close this issue now. Thanks for all your help and once again, awesome package!

**Comment by demianbrecht** [comment]
No worries.
